// <auto-generated />
using System;
using LyncasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LyncasAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220420133945_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LyncasAPI.Models.Autenticacao", b =>
                {
                    b.Property<int>("IdPessoaAutenticacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoaAutenticacao"), 1L, 1);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdPessoaAutenticacao");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Autenticacao");

                    b.HasData(
                        new
                        {
                            IdPessoaAutenticacao = 1,
                            Senha = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Status = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LyncasAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"), 1L, 1);

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdPessoa");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pessoa");

                    b.HasData(
                        new
                        {
                            IdPessoa = 1,
                            DataDeNascimento = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            Nome = "Admin",
                            Sobrenome = "admin",
                            Telefone = "4799999999"
                        });
                });

            modelBuilder.Entity("LyncasAPI.Models.Autenticacao", b =>
                {
                    b.HasOne("LyncasAPI.Models.Pessoa", "User")
                        .WithOne("autenticacao")
                        .HasForeignKey("LyncasAPI.Models.Autenticacao", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LyncasAPI.Models.Pessoa", b =>
                {
                    b.Navigation("autenticacao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
